before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    binary: aca
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.commit={{.FullCommit}}
      - -X main.version={{.Version}}
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64
      - darwin_amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - maintainer: Brandon Wagner
    description: |-
      a CLI to analyze API calls to AWS
    license: Apache-2.0
    formats:
      - deb
      - rpm
